### PR TITLE
Cantonese

### PR DESCRIPTION
**Pull request by indiejoseph**

### CODE REVIEW

**Comment by lq0104** [comment]
Sorry to ask here, I couldn't find the entry for issues. I would like to know how the current Cantonese voice sounds and if there are any demos available to listen to.

**Comment by indiejoseph** [comment]
Here is the sample generated by our previous model, and we are training the next version with new g2p conversation.

[tmp_gradio_724a507c89ddd43013617975303510a5d9328ef2_audio.wav.zip](https://github.com/user-attachments/files/15927722/tmp_gradio_724a507c89ddd43013617975303510a5d9328ef2_audio.wav.zip)

**Comment by lq0104** [comment]
Hi, sorry to disturb you, there is another question. How can I generate speech through TTS model? I saw in the link https://huggingface.co/hon9kon9ize/bert-vits2-cantonese has trained models, but I don't know how to use it. sorry about I don't know much about this field,  and I  couldn't find any instructions in the Readme file on the homepage.

**Comment by indiejoseph** [comment]
You can download the pretrained model in a local directory and then specify the folder location webui -> model in config.yml. and then run webui.py

if you cannot found the config.yml in the repo root folder, you can copy and paste the default_config.yml and rename it to config.yml

**Comment by lq0104** [comment]
Cool, it can now run, and the effect feels good! Does it support SSML (Speech Synthesis Markup Language)?

**Comment by indiejoseph** [comment]
Not actually, but you can modify it to feed Jyutping directly instead of text

**Comment by lq0104** [comment]
I may not have explained it clearly. What I mean is, can we add some emotions to the TTS voice, such as happiness or sadness, or insert some laughter, sighs, and so on

**Comment by indiejoseph** [comment]
you can check [Bert-Vits2 ](https://github.com/fishaudio/Bert-VITS2/blob/4e3e589995cd28e0481b6e2db2e89a7bd64e94b6/oldVersion/V210/emo_gen.py#L36) there was a version that support emotion, but our pretrain weights doesnt support it

**Comment by lq0104** [comment]
Hi, when I tested the "mix" mode, I encountered an error. My input text is "[EN_SPK86]\<en\> hello \<yue\>粵語",  and get error message:

>   File "webui.py", line 345, in tts_fn
>     audio_list = process_text(
>   File "webui.py", line 274, in process_text
>     generate_audio_multilang(
>   File "webui.py", line 115, in generate_audio_multilang
>     audio = infer_multilang(
>   File "/home/zy/data8ta/lq/code/Bert-VITS2-Cantonese/infer.py", line 384, in infer_multilang
>     net_g.infer(
>   File "/home/zy/data8ta/lq/code/Bert-VITS2-Cantonese/models.py", line 1099, in infer
>     g = self.emb_g(sid).unsqueeze(-1)  # [b, h, 1]
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/sparse.py", line 162, in forward
>     return F.embedding(
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2233, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got 
> torch.cuda.FloatTensor instead (while checking arguments for embedding)

and I changed code   
https://github.com/hon9kon9ize/Bert-VITS2-Cantonese/blob/aff70657b8cc54e585d7a34b54bec6eb543fd55b/infer.py#L383

        audio = (
            net_g.infer(
                x_tst,
                x_tst_lengths,
                speakers,
                tones,
                lang_ids,
                en_bert,
                yue_bert,
                sdp_ratio=sdp_ratio,
                noise_scale=noise_scale,
                noise_scale_w=noise_scale_w,
                length_scale=length_scale,
            )[0][0, 0]
TO

        audio = (
            net_g.infer(
                x_tst,
                x_tst_lengths,
                tones,
                lang_ids,
                en_bert,
                yue_bert,
                speakers,
                sdp_ratio=sdp_ratio,
                noise_scale=noise_scale,
                noise_scale_w=noise_scale_w,
                length_scale=length_scale,
            )[0][0, 0]

everything is OK, It seems that there might be an issue with the position of the `speakers` parameter when using the "mix" mode.

**Pull request merged**
